server:
  port: 8888
  servlet:
    context-path: /duscrumtool

spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/duscrumtool?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
